### ISSUE TITLE
Create option to hide side bar.

### ISSUE THREAD

**Issue by qcgilbert** [lowercasename/gathio#126] opened 2024-01-19 01:41 UTC
Create an option to hide side bar to prevent new events being created.

**Comment by lowercasename** [comment] 2024-02-06 10:51
This won't really prevent new events being created as the URL to open the event form will still exist. What's your use case for preventing events from being created? We can probably add an option to properly lock down an instance.

**Comment by qcgilbert** [comment] 2024-02-06 11:12
I integrate this as a part of another site (not strip the branding or
anything like that).  I want to share events but limit who can create them.

I think requiring a password to create events or a magic url could work.

I was looking for a quick and dirty solution via css as opposed to making
more work for anyone :)

**Comment by dev-nicolaos** [comment] 2024-02-06 16:44
If the motivation here is to limit who can create events, I think this issue is a duplicate of #1

**Closed** 2024-02-06 16:53 UTC
