### ISSUE TITLE
No Mastodon DM after following event account

### ISSUE THREAD

**Issue by jasontucker** [lowercasename/gathio#78] opened 2022-11-10 23:42 UTC
Greetings, after making an event and sending the account name for folks to search for on mastodon and follow it they never got a DM with a poll link, is this still the method of RSVPing on mastodon?

**Comment by lowercasename** [comment] 2022-11-13 19:31
Hi! Could you see if the issue is resolved with the newest version in the main branch (which is now active on the gath.io site)?

**Comment by amwelles** [comment] 2022-11-14 19:13
I just tried this, and I also did not receive the DM.

**Comment by lowercasename** [comment] 2022-11-17 17:01
I can confirm that I also am not getting DMs on Mastodon and my follow requests aren't being accepted.

I did some logging and digging around in the code and it looks like this block may be causing an issue: https://github.com/lowercasename/gathio/blob/master/routes.js#L1927-L1934

During this request from Mastodon:

```
{
  '@context': 'https://www.w3.org/ns/activitystreams',
  id: 'https://weirder.earth/a7cd1e65-de7e-4689-8173-898ce0c7b75a',
  type: 'Follow',
  actor: 'https://weirder.earth/users/lown',
  object: 'https://dev.gath.io/11DSAIKd3fWZQiBzt7RKu'
}
```

The request the code above that block makes to `https://weirder.earth/users/lown#main-key` is:

```
Request not signed
```
Rather than a JSON of the actor. Not sure why this is happening! Looks like Mastodon may want more than just the headers we're currently sending.

Subsequently, the block of code I highlighted then fails.

This might be connected to the issues being reported in https://github.com/lowercasename/gathio/issues/81 (cf. @dariusk if this helps you!)

**Comment by dariusk** [comment] 2022-11-17 17:14
This is helpful yes, thanks!

**Comment by kousu** [comment] 2022-11-17 17:26
> this block may be causing an issue: https://github.com/lowercasename/gathio/blob/master/routes.js#L1927-L1934

For the future, here's the permalink!

https://github.com/lowercasename/gathio/blob/e93b23db71df18480b29ed53c1b8247e7f0f83a7/routes.js#L1927-L1934

**Comment by lowercasename** [comment] 2022-11-18 10:56
@dariusk No, after a few hours there's still no DM and the follow request is unaccepted.

**Comment by dariusk** [comment] 2022-11-18 15:37
@lowercasename where are you attempting to follow from? (sorry but this all helps me debug)

**Comment by lowercasename** [comment] 2024-02-05 21:50
I think this has been resolved by other AP work we've done since I've been receiving DMs as expected for a while now.

**Closed by lowercasename** 2024-02-05 21:50 UTC
Labels: bug, federation
